import { generateTimestamps, visitingHours } from "@/mockConstants";
import { User } from "@/schemas/usersSchemas";

export const users: User[] = [
  {
    user_id: "50654654",
    slug: "vanmokum",
    user_name: "VANMOKUM",
    short_description: "High-end lighting and furniture brands",
    type: "participant",
    is_sticky: true,
    year: 1998,
    is_mod: true,
    status: "accepted",
    plan_id: "planId-3",
    description:
      "At VANMOKUM we take care of the development, manufacturing and distribution of high-end lighting and furniture brands:\n\nGRAYPANTS\nFRAMA\nPIET HEIN EEK LIGHTING\nAY ILLUMINATE\nSELETTI\nJAPTH\n\nAt GLUE'24, our PANDVANMOKUM will also be the place to discover work from external brands and designers:\n\nNLXLxSTUDIO JOB\nARTLINEZ\nJAN WILLEM KALDENBACH\nSUPA DUPA STUDIO\nSTUDIO RENS\nVANJOOSTxKEGEL\nDIRK DUIF\nTEUN ZWETS",
    invoice_data: {
      ...generateTimestamps(),
      invoice_id: "invoice-user50654654",
      user_id: "50654654",
      invoice_data: {
        invoice_company_name: "VANMOKUM",
        invoice_zip_code: "1071 XX",
        invoice_address: "Museumstraat 1",
        invoice_country: "Netherlands",
        invoice_city: "Amsterdam",
        invoice_extra: "Extra data",
      },
    },
    map_id: { id: "place-7291" },
    visiting_hours: visitingHours,
    phone_number: ["+31 (0)20 21 03 101", "+31 (0)20 21 03 101"],
    visible_email: ["press@vanmokum.com", "press@vanmokum.com"],
    visible_website: ["/members/vanmokum"],
    social_media: {
      instagramLink: "https://www.instagramLink.com/vanmokum/",
      facebookLink: "https://www.facebookLink.com/VANMOKUM/",
      linkedinLink: "https://www.linkedinLink.com/company/vanmokum",
    },
    images: [
      {
        image_name: "vanmokum-carousel-image-1",
        image_url: `/placeholders/user-placeholder-1.jpg`,
        alt: "vanmokum profile image 1",
        ...generateTimestamps(),
      },
      {
        image_name: "vanmokum-carousel-image-2",
        image_url: `/placeholders/user-placeholder-2.jpg`,
        alt: "vanmokum profile image 2",
        ...generateTimestamps(),
      },
      {
        image_name: "vanmokum-carousel-image-3",
        image_url: `/placeholders/user-placeholder-3.jpg`,
        alt: "vanmokum profile image 3",
        ...generateTimestamps(),
      },
    ],
    email: "press@vanmokum.com",
    password: "password",
    ...generateTimestamps(),
  },

  {
    user_id: "50654654654",
    slug: "vanmokumsdfs",
    user_name: "VANMOKUMere",
    short_description: "High-end lighting and furniture brands",
    type: "participant",
    is_sticky: true,
    year: 1998,
    is_mod: false,
    status: "accepted",
    plan_id: "planId-3",
    description:
      "At VANMOKUM we take care of the development, manufacturing and distribution of high-end lighting and furniture brands:\n\nGRAYPANTS\nFRAMA\nPIET HEIN EEK LIGHTING\nAY ILLUMINATE\nSELETTI\nJAPTH\n\nAt GLUE'24, our PANDVANMOKUM will also be the place to discover work from external brands and designers:\n\nNLXLxSTUDIO JOB\nARTLINEZ\nJAN WILLEM KALDENBACH\nSUPA DUPA STUDIO\nSTUDIO RENS\nVANJOOSTxKEGEL\nDIRK DUIF\nTEUN ZWETS",
    invoice_data: {
      ...generateTimestamps(),
      invoice_id: "invoice-user50654654",
      user_id: "50654654",
      invoice_data: {
        invoice_company_name: "VANMOKUM",
        invoice_zip_code: "1071 XX",
        invoice_address: "Museumstraat 1",
        invoice_country: "Netherlands",
        invoice_city: "Amsterdam",
        invoice_extra: "Extra data",
      },
    },
    map_id: { id: "place-8402" },
    visiting_hours: visitingHours,
    phone_number: ["+31 (0)20 21 03 101"],
    visible_email: ["press@vanmokum.com"],
    visible_website: ["/members/vanmokum"],
    social_media: {
      instagramLink: "https://www.instagramLink.com/vanmokum/",
      facebookLink: "https://www.facebookLink.com/VANMOKUM/",
      linkedinLink: "https://www.linkedinLink.com/company/vanmokum",
    },
    images: [
      {
        image_name: "vanmokum-carousel-image-1",
        image_url: `/placeholders/user-placeholder-1.jpg`,
        alt: "vanmokum profile image 1",
        ...generateTimestamps(),
      },
      {
        image_name: "vanmokum-carousel-image-2",
        image_url: `/placeholders/user-placeholder-2.jpg`,
        alt: "vanmokum profile image 2",
        ...generateTimestamps(),
      },
      {
        image_name: "vanmokum-carousel-image-3",
        image_url: `/placeholders/user-placeholder-3.jpg`,
        alt: "vanmokum profile image 3",
        ...generateTimestamps(),
      },
    ],
    email: "press@vanmokum.com",
    password: "password",
    ...generateTimestamps(),
  },
  {
    user_id: "50654655",
    slug: "studio-job",
    user_name: "STUDIO JOB",
    short_description: "Artistic design studio",
    type: "participant",
    is_sticky: false,
    is_mod: false,
    status: "accepted",
    plan_id: "planId-3",
    description:
      "STUDIO JOB blends fine art and design to create extraordinary pieces. Known for intricate sculptures and limited-edition works.",
    invoice_data: {
      ...generateTimestamps(),
      invoice_id: "invoice-user50654655",
      user_id: "50654655",
      invoice_data: {
        invoice_company_name: "STUDIO JOB",
        invoice_zip_code: "1071 DJ",
        invoice_address: "Museumplein 6",
        invoice_country: "Netherlands",
        invoice_city: "Amsterdam",
      },
    },
    map_id: { id: "place-9153" },
    visiting_hours: visitingHours,
    phone_number: ["+31 (0)20 22 04 102"],
    visible_email: ["info@studiojob.com"],
    visible_website: ["/members/studio-job"],
    social_media: {
      instagramLink: "https://www.instagramLink.com/studiojob/",
      facebookLink: "https://www.facebookLink.com/studiojobdesign/",
      linkedinLink: "https://www.linkedinLink.com/company/studiojob",
    },
    images: [
      {
        image_name: "studio-job-carousel-image-1",
        image_url: `/placeholders/user-placeholder-1.jpg`,
        alt: "studio-job profile image 1",
        ...generateTimestamps(),
      },
      {
        image_name: "studio-job-carousel-image-2",
        image_url: `/placeholders/user-placeholder-2.jpg`,
        alt: "studio-job profile image 2",
        ...generateTimestamps(),
      },
      {
        image_name: "studio-job-carousel-image-3",
        image_url: `/placeholders/user-placeholder-3.jpg`,
        alt: "studio-job profile image 3",
        ...generateTimestamps(),
      },
    ],
    email: "info@studiojob.com",
    password: "password",
    ...generateTimestamps(),
  },
  {
    user_id: "5065465985",
    slug: "studio-rens",
    user_name: "STUDIO RENS",
    short_description: "Color-focused design studio",
    type: "participant",
    is_sticky: false,
    is_mod: false,
    status: "pending",
    plan_id: "planId-3",
    description:
      "STUDIO RENS explores the essence of color, collaborating with various brands to challenge the perception of material and color.",
    invoice_data: {
      ...generateTimestamps(),
      invoice_id: "invoice-user5065465985",
      user_id: "5065465985",
      invoice_data: {
        invoice_company_name: "STUDIO RENS",
        invoice_zip_code: "1016 GV",
        invoice_address: "Westermarkt 20",
        invoice_country: "Netherlands",
        invoice_city: "Amsterdam",
      },
    },
    map_id: { id: "place-1029" },
    visiting_hours: visitingHours,
    phone_number: ["+31 (0)20 22 04 202"],
    visible_email: ["info@studiorens.com"],
    visible_website: ["/members/studio-rens"],
    social_media: {
      instagramLink: "https://www.instagramLink.com/studiorens/",
      facebookLink: "https://www.facebookLink.com/studiorens/",
      linkedinLink: "https://www.linkedinLink.com/company/studiorens",
    },
    images: [
      {
        image_name: "studio-rens-carousel-image-1",
        image_url: `/placeholders/user-placeholder-1.jpg`,
        alt: "studio rens profile image 1",
        ...generateTimestamps(),
      },
      {
        image_name: "studio-rens-carousel-image-2",
        image_url: `/placeholders/user-placeholder-2.jpg`,
        alt: "studio rens profile image 2",
        ...generateTimestamps(),
      },
      {
        image_name: "studio-rens-carousel-image-3",
        image_url: `/placeholders/user-placeholder-3.jpg`,
        alt: "studio rens profile image 3",
        ...generateTimestamps(),
      },
    ],
    email: "info@studiorens.com",
    password: "password",
    ...generateTimestamps(),
  },
  {
    user_id: "50654656",
    slug: "ay-illuminate",
    user_name: "AY ILLUMINATE",
    short_description: "Innovative lighting design",
    type: "participant",
    is_sticky: false,
    is_mod: false,
    status: "accepted",
    plan_id: "planId-2",
    description:
      "AY ILLUMINATE is dedicated to crafting unique lighting solutions that enhance the beauty of spaces. Each piece tells a story.",
    invoice_data: {
      ...generateTimestamps(),
      invoice_id: "invoice-user50654656",
      user_id: "50654656",
      invoice_data: {
        invoice_company_name: "AY ILLUMINATE",
        invoice_zip_code: "1071 JS",
        invoice_address: "Hobbemastraat 5",
        invoice_country: "Netherlands",
        invoice_city: "Amsterdam",
      },
    },
    map_id: { id: "place-1724" },
    visiting_hours: visitingHours,
    phone_number: ["+31 (0)20 22 00 300"],
    visible_email: ["contact@ayilluminate.com"],
    visible_website: ["/members/ay-illuminate"],
    social_media: {
      instagramLink: "https://www.instagramLink.com/ayilluminate/",
      facebookLink: "https://www.facebookLink.com/ayilluminate/",
      linkedinLink: "https://www.linkedinLink.com/company/ayilluminate",
    },
    images: [
      {
        image_name: "ay-illuminate-carousel-image-1",
        image_url: `/placeholders/user-placeholder-1.jpg`,
        alt: "ay illuminate profile image 1",
        ...generateTimestamps(),
      },
      {
        image_name: "ay-illuminate-carousel-image-2",
        image_url: `/placeholders/user-placeholder-2.jpg`,
        alt: "ay illuminate profile image 2",
        ...generateTimestamps(),
      },
      {
        image_name: "ay-illuminate-carousel-image-3",
        image_url: `/placeholders/user-placeholder-3.jpg`,
        alt: "ay illuminate profile image 3",
        ...generateTimestamps(),
      },
    ],
    email: "contact@ayilluminate.com",
    password: "password",
    ...generateTimestamps(),
  },
  {
    user_id: "50654657",
    slug: "nlxl",
    user_name: "NLXL",
    short_description: "Unique wallpaper designs",
    type: "participant",
    is_sticky: false,
    is_mod: false,
    status: "accepted",
    plan_id: "planId-2",
    description:
      "NLXL specializes in high-quality wallpaper designs that are both innovative and artistic. Our collections are inspired by various cultures and styles.",
    invoice_data: {
      ...generateTimestamps(),
      invoice_id: "invoice-user50654657",
      user_id: "50654657",
      invoice_data: {
        invoice_company_name: "NLXL",
        invoice_zip_code: "1015 BG",
        invoice_address: "Keizersgracht 204",
        invoice_country: "Netherlands",
        invoice_city: "Amsterdam",
      },
    },
    map_id: { id: "place-2598" },
    visiting_hours: visitingHours,
    phone_number: ["+31 (0)20 22 00 400"],
    visible_email: ["info@nlxl.com"],
    visible_website: ["/members/nlxl"],
    social_media: {
      instagramLink: "https://www.instagramLink.com/nlxl/",
      facebookLink: "https://www.facebookLink.com/NLXL/",
      linkedinLink: "https://www.linkedinLink.com/company/nlxl",
    },
    images: [
      {
        image_name: "nlxl-carousel-image-1",
        image_url: `/placeholders/user-placeholder-1.jpg`,
        alt: "nlxl profile image 1",
        ...generateTimestamps(),
      },
      {
        image_name: "nlxl-carousel-image-2",
        image_url: `/placeholders/user-placeholder-2.jpg`,
        alt: "nlxl profile image 2",
        ...generateTimestamps(),
      },
      {
        image_name: "nlxl-carousel-image-3",
        image_url: `/placeholders/user-placeholder-3.jpg`,
        alt: "nlxl profile image 3",
        ...generateTimestamps(),
      },
    ],
    email: "info@nlxl.com",
    password: "password",
    ...generateTimestamps(),
  },
  {
    user_id: "50654658",
    slug: "frama",
    user_name: "FRAMA",
    short_description: "Design studio and manufacturer",
    type: "participant",
    is_sticky: false,
    is_mod: false,
    status: "accepted",
    plan_id: "planId-2",
    description:
      "FRAMA is a design studio and manufacturer known for its minimalist approach and craftsmanship in furniture, lighting, and interiors.",
    invoice_data: {
      ...generateTimestamps(),
      invoice_id: "invoice-user50654658",
      user_id: "50654658",
      invoice_data: {
        invoice_company_name: "FRAMA",
        invoice_zip_code: "1043 AD",
        invoice_address: "Zaanstraat 11",
        invoice_country: "Netherlands",
        invoice_city: "Amsterdam",
      },
    },
    map_id: { id: "place-3497" },
    visiting_hours: visitingHours,
    phone_number: ["+31 (0)20 22 00 500"],
    visible_email: ["info@frama.com"],
    visible_website: ["/members/frama"],
    social_media: {
      instagramLink: "https://www.instagramLink.com/frama/",
      facebookLink: "https://www.facebookLink.com/frama/",
      linkedinLink: "https://www.linkedinLink.com/company/frama",
    },
    images: [
      {
        image_name: "frama-carousel-image-1",
        image_url: `/placeholders/user-placeholder-1.jpg`,
        alt: "frama profile image 1",
        ...generateTimestamps(),
      },
      {
        image_name: "frama-carousel-image-2",
        image_url: `/placeholders/user-placeholder-2.jpg`,
        alt: "frama profile image 2",
        ...generateTimestamps(),
      },
      {
        image_name: "frama-carousel-image-3",
        image_url: `/placeholders/user-placeholder-3.jpg`,
        alt: "frama profile image 3",
        ...generateTimestamps(),
      },
    ],
    email: "info@frama.com",
    password: "password",
    ...generateTimestamps(),
  },
  {
    user_id: "654654984",
    slug: "framaSecondOne",
    user_name: "FRAMAdsdfsd",
    short_description: "Design studio and manufacturer",
    type: "participant",
    is_sticky: false,
    is_mod: false,
    status: "accepted",
    plan_id: "planId-2",
    description:
      "FRAMA is a design studio and manufacturer known for its minimalist approach and craftsmanship in furniture, lighting, and interiors.",
    invoice_data: {
      ...generateTimestamps(),
      invoice_id: "invoice-user654654984",
      user_id: "654654984",
      invoice_data: {
        invoice_company_name: "FRAMA",
        invoice_zip_code: "1043 AD",
        invoice_address: "Zaanstraat 11",
        invoice_country: "Netherlands",
        invoice_city: "Amsterdam",
      },
    },
    visiting_hours: visitingHours,
    phone_number: ["+31 (0)20 22 00 500"],
    visible_email: ["info@frama.com"],
    visible_website: ["/members/frama"],
    social_media: {
      instagramLink: "https://www.instagramLink.com/frama/",
      facebookLink: "https://www.facebookLink.com/frama/",
      linkedinLink: "https://www.linkedinLink.com/company/frama",
    },
    images: [
      {
        image_name: "frama-carousel-image-1",
        image_url: `/placeholders/user-placeholder-1.jpg`,
        alt: "frama profile image 1",
        ...generateTimestamps(),
      },
      {
        image_name: "frama-carousel-image-2",
        image_url: `/placeholders/user-placeholder-2.jpg`,
        alt: "frama profile image 2",
        ...generateTimestamps(),
      },
      {
        image_name: "frama-carousel-image-3",
        image_url: `/placeholders/user-placeholder-3.jpg`,
        alt: "frama profile image 3",
        ...generateTimestamps(),
      },
    ],
    email: "info@frama.com",
    password: "password",
    ...generateTimestamps(),
    no_address: true,
  },

  {
    user_id: "789654123",
    slug: "graypantsStudio",
    user_name: "Graypants",
    short_description: "Lighting and product design studio",
    type: "participant",
    is_sticky: true,
    is_mod: false,
    status: "pending",
    plan_id: "planId-4",
    description:
      "Graypants is a lighting and product design studio based in Seattle, creating innovative solutions with a focus on sustainability.",
    invoice_data: {
      ...generateTimestamps(),
      invoice_id: "invoice-user789654123",
      user_id: "789654123",
      invoice_data: {
        invoice_company_name: "Graypants",
        invoice_zip_code: "98104",
        invoice_address: "200 S Jackson St",
        invoice_country: "USA",
        invoice_city: "Seattle",
      },
    },
    visiting_hours: visitingHours,
    phone_number: ["+1 (206) 123 4567"],
    visible_email: ["contact@graypants.com"],
    visible_website: ["/members/graypants"],
    social_media: {
      instagramLink: "https://www.instagramLink.com/graypants/",
      facebookLink: "https://www.facebookLink.com/graypants/",
      linkedinLink: "https://www.linkedinLink.com/company/graypants",
    },
    images: [
      {
        image_name: "graypants-carousel-image-1",
        image_url: `/placeholders/user-placeholder-1.jpg`,
        alt: "graypants profile image 1",
        ...generateTimestamps(),
      },
      {
        image_name: "graypants-carousel-image-2",
        image_url: `/placeholders/user-placeholder-2.jpg`,
        alt: "graypants profile image 2",
        ...generateTimestamps(),
      },
      {
        image_name: "graypants-carousel-image-3",
        image_url: `/placeholders/user-placeholder-3.jpg`,
        alt: "graypants profile image 3",
        ...generateTimestamps(),
      },
    ],
    email: "contact@graypants.com",
    password: "password",
    year: new Date().getFullYear(), // Fix: Add the required 'year' property
    ...generateTimestamps(),
    no_address: true,
  },
  {
    user_id: "963852741",
    slug: "selettiStudio",
    user_name: "Seletti",
    short_description: "Innovative design brand",
    type: "participant",
    is_sticky: false,
    is_mod: true,
    status: "accepted",
    plan_id: "planId-5",
    description:
      "Seletti stands out for innovative, quality designs combining pop art with unconventional aesthetics in furniture and lighting.",
    invoice_data: {
      ...generateTimestamps(),
      invoice_id: "invoice-user963852741",
      user_id: "963852741",
      invoice_data: {
        invoice_company_name: "Seletti",
        invoice_zip_code: "46019",
        invoice_address: "Via Marco Polo 23",
        invoice_country: "Italy",
        invoice_city: "Viadana",
      },
    },
    visiting_hours: visitingHours,
    phone_number: ["+39 0375 820 292"],
    visible_email: ["info@seletti.it"],
    visible_website: ["/members/seletti"],
    social_media: {
      instagramLink: "https://www.instagramLink.com/seletti/",
      facebookLink: "https://www.facebookLink.com/seletti/",
      linkedinLink: "https://www.linkedinLink.com/company/seletti",
    },
    images: [
      {
        image_name: "seletti-carousel-image-1",
        image_url: `/placeholders/user-placeholder-1.jpg`,
        alt: "seletti profile image 1",
        ...generateTimestamps(),
      },
      {
        image_name: "seletti-carousel-image-2",
        image_url: `/placeholders/user-placeholder-2.jpg`,
        alt: "seletti profile image 2",
        ...generateTimestamps(),
      },
      {
        image_name: "seletti-carousel-image-3",
        image_url: `/placeholders/user-placeholder-3.jpg`,
        alt: "seletti profile image 3",
        ...generateTimestamps(),
      },
    ],
    email: "info@seletti.it",
    password: "password",
    ...generateTimestamps(),
    no_address: true,
  },
];
