import { generateTimestamps, visitingHours } from "@/mockConstants";
import { User } from "@/schemas/usersSchemas";

export const users: User[] = [
  {
    userId: "50654654",
    slug: "vanmokum",
    userName: "VANMOKUM",
    shortDescription: "High-end lighting and furniture brands",
    type: "participant",
    isCurated: true,
    year: 1998,
    isMod: true,
    status: "accepted",
    planId: "planId-3",
    description:
      "At VANMOKUM we take care of the development, manufacturing and distribution of high-end lighting and furniture brands:\n\nGRAYPANTS\nFRAMA\nPIET HEIN EEK LIGHTING\nAY ILLUMINATE\nSELETTI\nJAPTH\n\nAt GLUE'24, our PANDVANMOKUM will also be the place to discover work from external brands and designers:\n\nNLXLxSTUDIO JOB\nARTLINEZ\nJAN WILLEM KALDENBACH\nSUPA DUPA STUDIO\nSTUDIO RENS\nVANJOOSTxKEGEL\nDIRK DUIF\nTEUN ZWETS",
    invoiceData: {
      ...generateTimestamps(),
      invoiceId: "invoice-user50654654",
      userId: "50654654",
      invoiceData: {
        invoiceCompanyName: "VANMOKUM",
        invoiceZipCode: "1071 XX",
        invoiceAddress: "Museumstraat 1",
        invoiceCountry: "Netherlands",
        invoiceCity: "Amsterdam",
        invoiceExtra: "Extra data",
      },
    },
    mapId: { id: "place-7291" },
    visitingHours: visitingHours,
    phoneNumber: ["+31 (0)20 21 03 101", "+31 (0)20 21 03 101"],
    visibleEmail: ["press@vanmokum.com", "press@vanmokum.com"],
    visibleWebsite: ["/members/vanmokum"],
    socialMedia: {
      instagramLink: "https://www.instagramLink.com/vanmokum/",
      facebookLink: "https://www.facebookLink.com/VANMOKUM/",
      linkedinLink: "https://www.linkedinLink.com/company/vanmokum",
    },
    images: [
      {
        imageName: "vanmokum-carousel-image-1",
        id: "vanmokum-carousel-image-1",
        imageUrl: `/placeholders/user-placeholder-1.jpg`,
        alt: "vanmokum profile image 1",
        ...generateTimestamps(),
      },
      {
        imageName: "vanmokum-carousel-image-2",
        id: "vanmokum-carousel-image-2",
        imageUrl: `/placeholders/user-placeholder-2.jpg`,
        alt: "vanmokum profile image 2",
        ...generateTimestamps(),
      },
      {
        imageName: "vanmokum-carousel-image-3",
        id: "vanmokum-carousel-image-3",
        imageUrl: `/placeholders/user-placeholder-3.jpg`,
        alt: "vanmokum profile image 3",
        ...generateTimestamps(),
      },
    ],
    email: "press@vanmokum.com",
    password: "password",
    ...generateTimestamps(),
  },

  {
    userId: "50654654654",
    slug: "vanmokumsdfs",
    userName: "VANMOKUMere",
    shortDescription: "High-end lighting and furniture brands",
    type: "participant",
    isCurated: true,
    year: 1998,
    isMod: false,
    status: "accepted",
    planId: "planId-3",
    description:
      "At VANMOKUM we take care of the development, manufacturing and distribution of high-end lighting and furniture brands:\n\nGRAYPANTS\nFRAMA\nPIET HEIN EEK LIGHTING\nAY ILLUMINATE\nSELETTI\nJAPTH\n\nAt GLUE'24, our PANDVANMOKUM will also be the place to discover work from external brands and designers:\n\nNLXLxSTUDIO JOB\nARTLINEZ\nJAN WILLEM KALDENBACH\nSUPA DUPA STUDIO\nSTUDIO RENS\nVANJOOSTxKEGEL\nDIRK DUIF\nTEUN ZWETS",
    invoiceData: {
      ...generateTimestamps(),
      invoiceId: "invoice-user50654654",
      userId: "50654654",
      invoiceData: {
        invoiceCompanyName: "VANMOKUM",
        invoiceZipCode: "1071 XX",
        invoiceAddress: "Museumstraat 1",
        invoiceCountry: "Netherlands",
        invoiceCity: "Amsterdam",
        invoiceExtra: "Extra data",
      },
    },
    mapId: { id: "place-8402" },
    visitingHours: visitingHours,
    phoneNumber: ["+31 (0)20 21 03 101"],
    visibleEmail: ["press@vanmokum.com"],
    visibleWebsite: ["/members/vanmokum"],
    socialMedia: {
      instagramLink: "https://www.instagramLink.com/vanmokum/",
      facebookLink: "https://www.facebookLink.com/VANMOKUM/",
      linkedinLink: "https://www.linkedinLink.com/company/vanmokum",
    },
    images: [
      {
        imageName: "vanmokum-carousel-image-1",
        id: "vanmokum-carousel-image-1",
        imageUrl: `/placeholders/user-placeholder-1.jpg`,
        alt: "vanmokum profile image 1",
        ...generateTimestamps(),
      },
      {
        imageName: "vanmokum-carousel-image-2",
        id: "vanmokum-carousel-image-2",
        imageUrl: `/placeholders/user-placeholder-2.jpg`,
        alt: "vanmokum profile image 2",
        ...generateTimestamps(),
      },
      {
        imageName: "vanmokum-carousel-image-3",
        id: "vanmokum-carousel-image-3",
        imageUrl: `/placeholders/user-placeholder-3.jpg`,
        alt: "vanmokum profile image 3",
        ...generateTimestamps(),
      },
    ],
    email: "press@vanmokum.com",
    password: "password",
    ...generateTimestamps(),
  },
  {
    userId: "50654655",
    slug: "studio-job",
    userName: "STUDIO JOB",
    shortDescription: "Artistic design studio",
    type: "participant",
    isCurated: false,
    isMod: false,
    status: "accepted",
    planId: "planId-3",
    description:
      "STUDIO JOB blends fine art and design to create extraordinary pieces. Known for intricate sculptures and limited-edition works.",
    invoiceData: {
      ...generateTimestamps(),
      invoiceId: "invoice-user50654655",
      userId: "50654655",
      invoiceData: {
        invoiceCompanyName: "STUDIO JOB",
        invoiceZipCode: "1071 DJ",
        invoiceAddress: "Museumplein 6",
        invoiceCountry: "Netherlands",
        invoiceCity: "Amsterdam",
      },
    },
    mapId: { id: "place-9153" },
    visitingHours: visitingHours,
    phoneNumber: ["+31 (0)20 22 04 102"],
    visibleEmail: ["info@studiojob.com"],
    visibleWebsite: ["/members/studio-job"],
    socialMedia: {
      instagramLink: "https://www.instagramLink.com/studiojob/",
      facebookLink: "https://www.facebookLink.com/studiojobdesign/",
      linkedinLink: "https://www.linkedinLink.com/company/studiojob",
    },
    images: [
      {
        imageName: "studio-job-carousel-image-1",
        id: "studio-job-carousel-image-1",
        imageUrl: `/placeholders/user-placeholder-1.jpg`,
        alt: "studio-job profile image 1",
        ...generateTimestamps(),
      },
      {
        imageName: "studio-job-carousel-image-2",
        id: "studio-job-carousel-image-2",
        imageUrl: `/placeholders/user-placeholder-2.jpg`,
        alt: "studio-job profile image 2",
        ...generateTimestamps(),
      },
      {
        imageName: "studio-job-carousel-image-3",
        id: "studio-job-carousel-image-3",
        imageUrl: `/placeholders/user-placeholder-3.jpg`,
        alt: "studio-job profile image 3",
        ...generateTimestamps(),
      },
    ],
    email: "info@studiojob.com",
    password: "password",
    ...generateTimestamps(),
  },
  {
    userId: "5065465985",
    slug: "studio-rens",
    userName: "STUDIO RENS",
    shortDescription: "Color-focused design studio",
    type: "participant",
    isCurated: false,
    isMod: false,
    status: "pending",
    planId: "planId-3",
    description:
      "STUDIO RENS explores the essence of color, collaborating with various brands to challenge the perception of material and color.",
    invoiceData: {
      ...generateTimestamps(),
      invoiceId: "invoice-user5065465985",
      userId: "5065465985",
      invoiceData: {
        invoiceCompanyName: "STUDIO RENS",
        invoiceZipCode: "1016 GV",
        invoiceAddress: "Westermarkt 20",
        invoiceCountry: "Netherlands",
        invoiceCity: "Amsterdam",
      },
    },
    mapId: { id: "place-1029" },
    visitingHours: visitingHours,
    phoneNumber: ["+31 (0)20 22 04 202"],
    visibleEmail: ["info@studiorens.com"],
    visibleWebsite: ["/members/studio-rens"],
    socialMedia: {
      instagramLink: "https://www.instagramLink.com/studiorens/",
      facebookLink: "https://www.facebookLink.com/studiorens/",
      linkedinLink: "https://www.linkedinLink.com/company/studiorens",
    },
    images: [
      {
        imageName: "studio-rens-carousel-image-1",
        id: "studio-rens-carousel-image-1",
        imageUrl: `/placeholders/user-placeholder-1.jpg`,
        alt: "studio rens profile image 1",
        ...generateTimestamps(),
      },
      {
        imageName: "studio-rens-carousel-image-2",
        id: "studio-rens-carousel-image-2",
        imageUrl: `/placeholders/user-placeholder-2.jpg`,
        alt: "studio rens profile image 2",
        ...generateTimestamps(),
      },
      {
        imageName: "studio-rens-carousel-image-3",
        id: "studio-rens-carousel-image-3",
        imageUrl: `/placeholders/user-placeholder-3.jpg`,
        alt: "studio rens profile image 3",
        ...generateTimestamps(),
      },
    ],
    email: "info@studiorens.com",
    password: "password",
    ...generateTimestamps(),
  },
  {
    userId: "50654656",
    slug: "ay-illuminate",
    userName: "AY ILLUMINATE",
    shortDescription: "Innovative lighting design",
    type: "participant",
    isCurated: false,
    isMod: false,
    status: "accepted",
    planId: "planId-2",
    description:
      "AY ILLUMINATE is dedicated to crafting unique lighting solutions that enhance the beauty of spaces. Each piece tells a story.",
    invoiceData: {
      ...generateTimestamps(),
      invoiceId: "invoice-user50654656",
      userId: "50654656",
      invoiceData: {
        invoiceCompanyName: "AY ILLUMINATE",
        invoiceZipCode: "1071 JS",
        invoiceAddress: "Hobbemastraat 5",
        invoiceCountry: "Netherlands",
        invoiceCity: "Amsterdam",
      },
    },
    mapId: { id: "place-1724" },
    visitingHours: visitingHours,
    phoneNumber: ["+31 (0)20 22 00 300"],
    visibleEmail: ["contact@ayilluminate.com"],
    visibleWebsite: ["/members/ay-illuminate"],
    socialMedia: {
      instagramLink: "https://www.instagramLink.com/ayilluminate/",
      facebookLink: "https://www.facebookLink.com/ayilluminate/",
      linkedinLink: "https://www.linkedinLink.com/company/ayilluminate",
    },
    images: [
      {
        imageName: "ay-illuminate-carousel-image-1",
        id: "ay-illuminate-carousel-image-1",
        imageUrl: `/placeholders/user-placeholder-1.jpg`,
        alt: "ay illuminate profile image 1",
        ...generateTimestamps(),
      },
      {
        imageName: "ay-illuminate-carousel-image-2",
        id: "ay-illuminate-carousel-image-2",
        imageUrl: `/placeholders/user-placeholder-2.jpg`,
        alt: "ay illuminate profile image 2",
        ...generateTimestamps(),
      },
      {
        imageName: "ay-illuminate-carousel-image-3",
        id: "ay-illuminate-carousel-image-3",
        imageUrl: `/placeholders/user-placeholder-3.jpg`,
        alt: "ay illuminate profile image 3",
        ...generateTimestamps(),
      },
    ],
    email: "contact@ayilluminate.com",
    password: "password",
    ...generateTimestamps(),
  },
  {
    userId: "50654657",
    slug: "nlxl",
    userName: "NLXL",
    shortDescription: "Unique wallpaper designs",
    type: "participant",
    isCurated: false,
    isMod: false,
    status: "accepted",
    planId: "planId-2",
    description:
      "NLXL specializes in high-quality wallpaper designs that are both innovative and artistic. Our collections are inspired by various cultures and styles.",
    invoiceData: {
      ...generateTimestamps(),
      invoiceId: "invoice-user50654657",
      userId: "50654657",
      invoiceData: {
        invoiceCompanyName: "NLXL",
        invoiceZipCode: "1015 BG",
        invoiceAddress: "Keizersgracht 204",
        invoiceCountry: "Netherlands",
        invoiceCity: "Amsterdam",
      },
    },
    mapId: { id: "place-2598" },
    visitingHours: visitingHours,
    phoneNumber: ["+31 (0)20 22 00 400"],
    visibleEmail: ["info@nlxl.com"],
    visibleWebsite: ["/members/nlxl"],
    socialMedia: {
      instagramLink: "https://www.instagramLink.com/nlxl/",
      facebookLink: "https://www.facebookLink.com/NLXL/",
      linkedinLink: "https://www.linkedinLink.com/company/nlxl",
    },
    images: [
      {
        imageName: "nlxl-carousel-image-1",
        id: "nlxl-carousel-image-1",
        imageUrl: `/placeholders/user-placeholder-1.jpg`,
        alt: "nlxl profile image 1",
        ...generateTimestamps(),
      },
      {
        imageName: "nlxl-carousel-image-2",
        id: "nlxl-carousel-image-2",
        imageUrl: `/placeholders/user-placeholder-2.jpg`,
        alt: "nlxl profile image 2",
        ...generateTimestamps(),
      },
      {
        imageName: "nlxl-carousel-image-3",
        id: "nlxl-carousel-image-3",
        imageUrl: `/placeholders/user-placeholder-3.jpg`,
        alt: "nlxl profile image 3",
        ...generateTimestamps(),
      },
    ],
    email: "info@nlxl.com",
    password: "password",
    ...generateTimestamps(),
  },
  {
    userId: "50654658",
    slug: "frama",
    userName: "FRAMA",
    shortDescription: "Design studio and manufacturer",
    type: "participant",
    isCurated: false,
    isMod: false,
    status: "accepted",
    planId: "planId-2",
    description:
      "FRAMA is a design studio and manufacturer known for its minimalist approach and craftsmanship in furniture, lighting, and interiors.",
    invoiceData: {
      ...generateTimestamps(),
      invoiceId: "invoice-user50654658",
      userId: "50654658",
      invoiceData: {
        invoiceCompanyName: "FRAMA",
        invoiceZipCode: "1043 AD",
        invoiceAddress: "Zaanstraat 11",
        invoiceCountry: "Netherlands",
        invoiceCity: "Amsterdam",
      },
    },
    mapId: { id: "place-3497" },
    visitingHours: visitingHours,
    phoneNumber: ["+31 (0)20 22 00 500"],
    visibleEmail: ["info@frama.com"],
    visibleWebsite: ["/members/frama"],
    socialMedia: {
      instagramLink: "https://www.instagramLink.com/frama/",
      facebookLink: "https://www.facebookLink.com/frama/",
      linkedinLink: "https://www.linkedinLink.com/company/frama",
    },
    images: [
      {
        imageName: "frama-carousel-image-1",
        id: "frama-carousel-image-1",
        imageUrl: `/placeholders/user-placeholder-1.jpg`,
        alt: "frama profile image 1",
        ...generateTimestamps(),
      },
      {
        imageName: "frama-carousel-image-2",
        id: "frama-carousel-image-2",
        imageUrl: `/placeholders/user-placeholder-2.jpg`,
        alt: "frama profile image 2",
        ...generateTimestamps(),
      },
      {
        imageName: "frama-carousel-image-3",
        id: "frama-carousel-image-3",
        imageUrl: `/placeholders/user-placeholder-3.jpg`,
        alt: "frama profile image 3",
        ...generateTimestamps(),
      },
    ],
    email: "info@frama.com",
    password: "password",
    ...generateTimestamps(),
  },
  {
    userId: "654654984",
    slug: "framaSecondOne",
    userName: "FRAMAdsdfsd",
    shortDescription: "Design studio and manufacturer",
    type: "participant",
    isCurated: false,
    isMod: false,
    status: "accepted",
    planId: "planId-2",
    description:
      "FRAMA is a design studio and manufacturer known for its minimalist approach and craftsmanship in furniture, lighting, and interiors.",
    invoiceData: {
      ...generateTimestamps(),
      invoiceId: "invoice-user654654984",
      userId: "654654984",
      invoiceData: {
        invoiceCompanyName: "FRAMA",
        invoiceZipCode: "1043 AD",
        invoiceAddress: "Zaanstraat 11",
        invoiceCountry: "Netherlands",
        invoiceCity: "Amsterdam",
      },
    },
    visitingHours: visitingHours,
    phoneNumber: ["+31 (0)20 22 00 500"],
    visibleEmail: ["info@frama.com"],
    visibleWebsite: ["/members/frama"],
    socialMedia: {
      instagramLink: "https://www.instagramLink.com/frama/",
      facebookLink: "https://www.facebookLink.com/frama/",
      linkedinLink: "https://www.linkedinLink.com/company/frama",
    },
    images: [
      {
        imageName: "frama-carousel-image-1",
        id: "frama-carousel-image-1",
        imageUrl: `/placeholders/user-placeholder-1.jpg`,
        alt: "frama profile image 1",
        ...generateTimestamps(),
      },
      {
        imageName: "frama-carousel-image-2",
        id: "frama-carousel-image-2",
        imageUrl: `/placeholders/user-placeholder-2.jpg`,
        alt: "frama profile image 2",
        ...generateTimestamps(),
      },
      {
        imageName: "frama-carousel-image-3",
        id: "frama-carousel-image-3",
        imageUrl: `/placeholders/user-placeholder-3.jpg`,
        alt: "frama profile image 3",
        ...generateTimestamps(),
      },
    ],
    email: "info@frama.com",
    password: "password",
    ...generateTimestamps(),
    noAddress: true,
  },

  {
    userId: "789654123",
    slug: "graypantsStudio",
    userName: "Graypants",
    shortDescription: "Lighting and product design studio",
    type: "participant",
    isCurated: true,
    isMod: false,
    status: "pending",
    planId: "planId-4",
    description:
      "Graypants is a lighting and product design studio based in Seattle, creating innovative solutions with a focus on sustainability.",
    invoiceData: {
      ...generateTimestamps(),
      invoiceId: "invoice-user789654123",
      userId: "789654123",
      invoiceData: {
        invoiceCompanyName: "Graypants",
        invoiceZipCode: "98104",
        invoiceAddress: "200 S Jackson St",
        invoiceCountry: "USA",
        invoiceCity: "Seattle",
      },
    },
    visitingHours: visitingHours,
    phoneNumber: ["+1 (206) 123 4567"],
    visibleEmail: ["contact@graypants.com"],
    visibleWebsite: ["/members/graypants"],
    socialMedia: {
      instagramLink: "https://www.instagramLink.com/graypants/",
      facebookLink: "https://www.facebookLink.com/graypants/",
      linkedinLink: "https://www.linkedinLink.com/company/graypants",
    },
    images: [
      {
        imageName: "graypants-carousel-image-1",
        id: "graypants-carousel-image-1",
        imageUrl: `/placeholders/user-placeholder-1.jpg`,
        alt: "graypants profile image 1",
        ...generateTimestamps(),
      },
      {
        imageName: "graypants-carousel-image-2",
        id: "graypants-carousel-image-2",
        imageUrl: `/placeholders/user-placeholder-2.jpg`,
        alt: "graypants profile image 2",
        ...generateTimestamps(),
      },
      {
        imageName: "graypants-carousel-image-3",
        id: "graypants-carousel-image-3",
        imageUrl: `/placeholders/user-placeholder-3.jpg`,
        alt: "graypants profile image 3",
        ...generateTimestamps(),
      },
    ],
    email: "contact@graypants.com",
    password: "password",
    year: new Date().getFullYear(), // Fix: Add the required 'year' property
    ...generateTimestamps(),
    noAddress: true,
  },
  {
    userId: "963852741",
    slug: "selettiStudio",
    userName: "Seletti",
    shortDescription: "Innovative design brand",
    type: "participant",
    isCurated: false,
    isMod: true,
    status: "accepted",
    planId: "planId-5",
    description:
      "Seletti stands out for innovative, quality designs combining pop art with unconventional aesthetics in furniture and lighting.",
    invoiceData: {
      ...generateTimestamps(),
      invoiceId: "invoice-user963852741",
      userId: "963852741",
      invoiceData: {
        invoiceCompanyName: "Seletti",
        invoiceZipCode: "46019",
        invoiceAddress: "Via Marco Polo 23",
        invoiceCountry: "Italy",
        invoiceCity: "Viadana",
      },
    },
    visitingHours: visitingHours,
    phoneNumber: ["+39 0375 820 292"],
    visibleEmail: ["info@seletti.it"],
    visibleWebsite: ["/members/seletti"],
    socialMedia: {
      instagramLink: "https://www.instagramLink.com/seletti/",
      facebookLink: "https://www.facebookLink.com/seletti/",
      linkedinLink: "https://www.linkedinLink.com/company/seletti",
    },
    images: [
      {
        imageName: "seletti-carousel-image-1",
        id: "seletti-carousel-image-1",
        imageUrl: `/placeholders/user-placeholder-1.jpg`,
        alt: "seletti profile image 1",
        ...generateTimestamps(),
      },
      {
        imageName: "seletti-carousel-image-2",
        id: "seletti-carousel-image-2",
        imageUrl: `/placeholders/user-placeholder-2.jpg`,
        alt: "seletti profile image 2",
        ...generateTimestamps(),
      },
      {
        imageName: "seletti-carousel-image-3",
        id: "seletti-carousel-image-3",
        imageUrl: `/placeholders/user-placeholder-3.jpg`,
        alt: "seletti profile image 3",
        ...generateTimestamps(),
      },
    ],
    email: "info@seletti.it",
    password: "password",
    ...generateTimestamps(),
    noAddress: true,
  },
];
